# Generated by Django 4.1.5 on 2023-02-18 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='artwork',
            field=models.ImageField(blank=True, null=True, upload_to='artworks/'),
        ),
    ]
