# Generated by Django 4.1.5 on 2023-02-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_post_description_post_hours_spent_post_used_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='hours_spent',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='used_material',
            field=models.TextField(),
        ),
    ]
