# Generated by Django 4.1.5 on 2023-02-28 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_post_created_at_alter_post_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='user',
        ),
    ]
