# Generated by Django 4.1.5 on 2023-02-28 14:01

from django.db import migrations


def add_tags(apps, schema_editor):
    PostTag = apps.get_model('web', 'PostTag')
    titles = ['Digital рисунок', 'Традиционный рисунок', 'Фотошоп', 'Граффити']
    for title in titles:
        postTag = PostTag(title=title)
        postTag.save()


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_rename_author_post_user'),
    ]

    operations = [
        migrations.RunPython(add_tags),
    ]
