# Generated by Django 4.1.5 on 2023-02-28 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0009_auto_20230228_1821'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posttag',
            options={'verbose_name': 'тег'},
        ),
        migrations.AddField(
            model_name='posttag',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='like',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.post', verbose_name='Пост'),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='post',
            name='art_type',
            field=models.CharField(max_length=50, verbose_name='Тип работы'),
        ),
        migrations.AlterField(
            model_name='post',
            name='artwork',
            field=models.ImageField(blank=True, null=True, upload_to='artworks/', verbose_name='Работа'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='post',
            name='hours_spent',
            field=models.IntegerField(verbose_name='Потрачено часов'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='web.posttag', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='post',
            name='used_material',
            field=models.TextField(verbose_name='Использованные материалы'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='posttag',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Название'),
        ),
    ]
